server:
  port: 10011
  servlet:
    context-path: content
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.130:3306/xczx?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: root
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml